AWSTemplateFormatVersion: 2010-09-09
Description: Create ECR repository and lifecycle policy
Parameters:
  RepositoryName:
    Type: String
    Default: flows
Resources:
  MyRepository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref RepositoryName